### ISSUE TITLE
DELETE /db causing the Listener to hang

### ISSUE THREAD

**Issue by jamiltz** [couchbase/couchbase-lite-java-core#1036]
Tested with #1032.

It may already have been fixed in #1034 

Logs: https://gist.github.com/jamiltz/fc8f2846a55d8f837367

Thread dump: https://gist.github.com/jamiltz/d7259d1602ca0d6caa26

**Comment by jamiltz** [comment]
Observations :
- The device was running replications and when user logs out the database is deleted. At this point, `database.close` is called.
- Seems like call to delete /db hanged the subsequent requests.

**Comment by hideki** [comment]
@jamiltz 

From thread-dump, this device run both Listener and Replicator. Could you please describe about application architecture how app uses Listener and Replicator?

Thanks!

**Comment by jamiltz** [comment]
It's a PhoneGap application so it uses the Listener for CRUD operations with the local database.

**Comment by hideki** [comment]
Notes to self:

- Thread 1 `CBLManagerWorkExecutor@23878` is WAITING in `Replicator.close()`
- Thread 2 `Acme.Utils.ThreadPool(2)` is WAITING for `Database.close()` 
- Thread 3 `CBLRequestWorker-ab0eb-0@23899` is BLOCKED  for `Database.open()` -> `ThreadPool(2)` - database instance
- Thread 4 `CBLRequestWorker-7980c-3@23946` is BLOCKED for  `Database.open()` -> `ThreadPool(2)` - database instance
- Thread 5 `Thread-8804@23956` is WAITING for `FutureTask.get()` in remote request retry
- Thread 6 `Acme.Utils.ThreadPool(0)` is BLOCKED in `Database.open()`  -> `ThreadPool(2)` - database instance
- Thread 7 `Acme.Utils.ThreadPool(3)` is BLOCKED in `Database.open()`  -> `ThreadPool(2)` - database instance
- 64 `CBLRequestWorker-xxx` is waiting
- many other threads are  WAITING/RUNNABLE/BLOCKED/TIMED_WAITING

**Comment by hideki** [comment]
Observation from thread-dump:
- Database.close() waits at following line. This line waits for all replicators will be shutdowned. This thread holds database instance as lock in `Router.do_DELETE_Database()`. 
https://github.com/couchbase/couchbase-lite-java-core/blob/11712fdec6aeaa192c80a9d302794ad1cedca740/src/main/java/com/couchbase/lite/Database.java#L1305-L1307
- Blocked threads are blocked at `Database.open()` which is synchronized method.

Observation from code review:
- By commit https://github.com/couchbase/couchbase-lite-java-core/commit/2839fc7978e4ace5c67795c1df9b14653e65ae79, `Router. do_DELETE_Database()` no longer holds database instance as lock.

**So this dead-lock should not be occurred with`0.0.0-577` build.**

NOTE: 
- As further task, we need to review Database open() and close() methods thread-safety. https://github.com/couchbase/couchbase-lite-java-core/issues/1038

**Comment by jamiltz** [comment]
The issue can be observed with build 0.0.0-577.

**Comment by hideki** [comment]
@jamiltz, Do you have thread-dump again?

**Comment by jamiltz** [comment]
Unfortunately not but I will try to provide that asap.

**Comment by jamiltz** [comment]
Here are the logs of another test with build 0.0.0-577

Thread dump 1: https://gist.github.com/jamiltz/7ffc6ad19169924da07b
Thread dump 2: https://gist.github.com/jamiltz/d6658b3a31877b49656e
Logs: https://gist.github.com/jamiltz/19fb50bc0cedb136b129

**Comment by hideki** [comment]
Note to self:

From thread dump 1:
- `"ChangeTracker-http://172.23.8.30:5984/ek0073@22235" prio=5 runnable` is waiting for response
- `Acme.Utils.ThreadPool(1)` is WAITING in Database.close() to wait all replicator stops
- `Acme.Utils.ThreadPool(2)` is WAITING in Database.close() to wait all replicator stops
- "CBLManagerWorkExecutor@22228" prio=5 waiting`in `PusherInternal.waitIfPaused()` because task is remaining in queue.
- `Acme.Utils.ThreadPool(0)` waits for /_changes with longpoll.

From thread dump 2:
- `ChangeTracker-http://172.23.8.30:5984/ek0073@22235` is waiting for response
- `Acme.Utils.ThreadPool(1)` is WAITING in Database.close() to wait all replicator stops
- `Acme.Utils.ThreadPool(2)` is WAITING in Database.close() to wait all replicator stops
- "CBLManagerWorkExecutor@22228" prio=5 waiting`in `PusherInternal.waitIfPaused()` because task is remaining in queue.
- `Acme.Utils.ThreadPool(0)` waits for /_changes with longpoll.
