### ISSUE TITLE
Push replication skipped 20 documents

### ISSUE THREAD

**Issue by jamiltz** [couchbase/couchbase-lite-java-core#1047]
Scenario: Device A is pushing and pulling with 4 other devices. So a total of 8 replications are running on Device A. When the user logs out from Device A, it stops the replications and deletes the database. While the user is logged out from Device A, 20 documents are added on each device (no active replications at this point). When the user logs back in Device A, all devices should have the same document count but it can sometimes happen that a device will be 20 documents behind in the total count. The replications are active again but this device will never receive the 20 documents that were skipped because the replicator has moved to tracking the last sequence number.

What's the most useful information I can provide to look into the root cause of this issue?

To begin, here's a thread dump of the device running the replications https://gist.github.com/jamiltz/df4b88c50e1e12ec3a05

**Comment by zgramana** [comment]
Can you please copy the APK off the laggard device and send it out-of-band the next time it happens? That way we can look inside the database to see what's actually going on.

**Comment by hideki** [comment]
@jamiltz,

##### I wrote the scenario. Please confirm.
1. Before user A logged out from device A, let assume all five devices have 10 documents.
1. User A logged out from device A, App on device A delete a database. Device A: no database, other 4 devices have 10 docs each.
1. On other 4 devices, Add 20 documents each. Other 4 devices have 30 documents. Let assume document ID is unique for all 80 docs.
1. User A logged in device A, then device A started to replicate to other 4 devices. 
1. Expectation: All devices have 90 documents.
1. Actual: some of devices have only 70 documents. 

##### Question to @jamiltz 
1. Does device A has 90 documents?
1. Are document IDs unique when other 4 devices add document?

If no for 1st question, there is failure to pull replication from one slave device
If yes for 1st question, there is failure to push replication to one slave device

**Comment by jamiltz** [comment]
Yes that's the scenario.

Answers:
1. Device A has 90 documents.
2. There is a _load docs_ button on the UI to insert 20 documents at a time. The document properties are the same on each button click. The doc ID is not specified so is uniquely generated by the database.

**Comment by jamiltz** [comment]
Here are the logs of device A. 10 replications were running but I filtered on IP `172.23.8.25` after noticing this remote db was missing some documents. Hopefully it can help find out why the push replication to `172.23.8.25` skipped some documents.

**Comment by zgramana** [comment]
This might happen if pusher updates that checkpoint, but meanwhile fails to actually push for some reason. `PusherInternal.removePending` might be the first place to look.

**Comment by hideki** [comment]
From thread-dump, one of Push replicator is in `paused` state which waits for some push tasks are processed. My assumption is push replication is super slow because of wifi connectivity. Or push failed with some reason, but push replicator recovery logic might have bug, then it can not recover from it. 
```
"CBLManagerWorkExecutor@23756" prio=5 waiting
  java.lang.Thread.State: WAITING
	 blocks CBLManagerWorkExecutor@23756
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Object.wait(Object.java:422)
	  at com.couchbase.lite.replicator.PusherInternal.waitIfPaused(PusherInternal.java:848)
	  - locked <0x5d6f> (a java.lang.Object)
	  at com.couchbase.lite.replicator.PusherInternal.changed(PusherInternal.java:393)
	  at com.couchbase.lite.Database.postChangeNotifications(Database.java:2267)
	  at com.couchbase.lite.Database.storageExitedTransaction(Database.java:703)
	  at com.couchbase.lite.store.SQLiteStore.endTransaction(SQLiteStore.java:2149)
	  at com.couchbase.lite.store.SQLiteStore.runInTransaction(SQLiteStore.java:680)
	  at com.couchbase.lite.replicator.PullerInternal.insertDownloads(PullerInternal.java:565)
	  at com.couchbase.lite.replicator.PullerInternal$1.process(PullerInternal.java:116)
	  at com.couchbase.lite.support.Batcher.processNow(Batcher.java:373)
	  - locked <0x5d70> (a java.lang.Object)
	  at com.couchbase.lite.support.Batcher.access$300(Batcher.java:17)
	  at com.couchbase.lite.support.Batcher$2.run(Batcher.java:307)
	  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
	  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
	  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	  at java.lang.Thread.run(Thread.java:818)
```

Next time, can you paste log message of slave device that can not get all documents.

**Comment by hideki** [comment]
Note to self:

As push replicator is paused state, WorkExecutor enters WAITING state to add new tasks (add new doc rev ids) in inbox. However, as WorkExecutor is blocked, `Batcher` can not process push tasks. Then, it causes dead-lock.

**Comment by hideki** [comment]
We should not pause in `Database.ChangeListener.changed()` because it could be called from UI thread or WorkExectutor. This pause mechanism was added to control a mount of push tasks at same time. Without control, it potentially consume a lot of memory if changed Document size is large or number of changed Document are a lot. To fix this issue, I will remove `waitIfPaused();`. But with other ticket, we need to implement better solution to control flow.

https://github.com/couchbase/couchbase-lite-java-core/blob/master/src/main/java/com/couchbase/lite/replicator/PusherInternal.java#L392-L393
```java
    public void changed(Database.ChangeEvent event) {
        List<DocumentChange> changes = event.getChanges();
        try {
            java.net.URI remoteUri = remote.toURI();
            for (DocumentChange change : changes) {
                // Skip revisions that originally came from the database I'm syncing to:
                URL source = change.getSource();
                if (source != null && source.toURI().equals(remoteUri))
                    return;
                RevisionInternal rev = change.getAddedRevision();
                if (getLocalDatabase().runFilter(filter, filterParams, rev)) {
                    pauseOrResume();
                    waitIfPaused();
                    // if not running state anymore, exit from loop.
                    if(!isRunning())
                        break;
                    RevisionInternal nuRev = rev.copy();
                    nuRev.setBody(null); //save memory
                    addToInbox(nuRev);
                }
            }
        } catch (java.net.URISyntaxException uriException) {
            // Not possible since it would not be an active replicator.
            // However, until we refactor everything to use java.net,
            // I'm not sure we have a choice but to swallow this.
            Log.e(Log.TAG_SYNC, "Active replicator found with invalid URI", uriException);
        }
    }
```

**Comment by jamiltz** [comment]
The issue can still be observed with build 589.

**Comment by hideki** [comment]
Notes from reviewing log files, thread-dump, and images files that @jamiltz provided. This information was based on build 577.

- From `/_active_tasks` response from the master device, all four pull replications were pending or hanging.
- From images of query results, all 5 devices including master devices had different number of total documents. `total_rows` should be same for all 5 devices. At least, it should be more than 420 docs.
- From thread-dump, it indicates push replicator hanged on master device.

Based on above observations, push replicator hanged because of dead-lock issue, then it made pull replicators hanged also because all eight (4 for push, 4 for pull) replicators use Batcher which is executed by WorkExecutor which is single thread.

However, dead-lock at push replicator was fixed by https://github.com/couchbase/couchbase-lite-java-core/commit/eefae52aa35c2a94bc097d4a3bbba896af1ef601 (Build 589) . It seems there is another issue that causes this problem.

To continue to investigate, we needs new thread-dump, log file from both master and slave devices.

**Comment by jamiltz** [comment]
New test where I logged out from slave device.

Thread dump of master device: https://gist.github.com/jamiltz/c76ed8d11a94319cd848
Thread dump of slave device: https://gist.github.com/jamiltz/9eadf7b3b51b5e5298ec

**Comment by hideki** [comment]
##### Observations from debugging with @james

1. It seems that replications are not hanging, it seems replications are slow because of too many replicators (10) and too many changes?
⋅⋅1. Connectivity document -> Don't update every 5 sec. 7000 document changes out of 8000 are for connectivity documents.
⋅⋅1. Use isExternal property to check where updates are come from.

1. From thread dump: https://gist.github.com/jamiltz/c76ed8d11a94319cd848#file-thread-dump-master-L36-L65 Router.do_GET_Document_changes was holding SQLite connection which is only one. In this method, it calls JavaScript filter. Because this holds SQLiteConnection, all other threads wait for SQLiteConnection. As @james said, since property is always 0 or not set. `/_changes` API always calls JavaScript filter <number of changes> times. With @james test env, it is 8000 changes because of Connectivity document.
⋅⋅* Please use `since` property for /_changes REST API
⋅⋅* Please review JavaScript filter if it does not cause infinite loop and execute unnecessary optation. 
⋅⋅* If possible, write Java filter instead of JavaScript filter. Java filter is much faster.

##### ToDo (Hideki)
- Check synchronized block `synchronized(store)` <-- many replicators wait at this. Maybe this is reason for slowness, review this.
- Currently SQLite connection is only one. By enable Write-Ahead-Log (WAL) from API, SQLiteDatabase create multiple connections. This should be experimented.
- Consider `runFilter()` out of cursor loop

**Comment by hideki** [comment]
Note to self:

From thread-dump from slave device, it also indicates `/_changes` API with JavaScript filter holds SQLite connection. JavaScript filter is relatively slower than Java one. Few other threads are waiting SQLite connection.
