### ISSUE TITLE
Build using project's gradle

### ISSUE THREAD

**Issue by zgramana** [couchbase/couchbase-lite-java-core#1084]
Eliminate external build scripts by building using existing gradle build scripts.

**Comment by michaelkwok** [comment]
This needs to be a join effort between Dev and Build team.  The idea I had with Zack was for me to work with Dev to refactor and maintain the gradle build project to reduce the number of external steps/stages in the build process.  Ideally, gradle should build everything in a single run.  This approach allows Dev to update and change the way things get built with ease.  Otherwise, it would require that I make specific custom changes to my build script.  Not to mention we can reduce the build time along the way.  The same idea needs to be applied to couchbase-lite-android but we will start with Java first.
