### ISSUE TITLE
Replication, Threading, and Lifecycle Issues

### ISSUE THREAD

**Issue by dougkoellmer** [couchbase/couchbase-lite-java-core#1212]
This isn't really a hard bug report. Rather a list of related issues that might range from bug to feature to "Oh that's mentioned in the docs" to "oh we purposely chose this design pattern because of X" depending on how you look at it. Nonetheless they all became issues for our specific use cases that we had to work around, so I figured I would mention them. These are all in reference to `1.2.1` on Android, but probably not exclusive to that version.

* `Database.close()` can block the thread it's called from indefinitely, or at least practically indefinitely (60 seconds). There are two reasons I found:
  * If you explicitly call `Replication.stop()` right before `Database.close()`, there's a race condition where [this line](https://github.com/couchbase/couchbase-lite-java-core/blob/master/src/main/java/com/couchbase/lite/Database.java#L1871) can get hit before [this line](https://github.com/couchbase/couchbase-lite-java-core/blob/master/src/main/java/com/couchbase/lite/Database.java#L1289).
  * I originally had 3 active `Replication`s going at the same time. After letting `Database.close()` handle stopping a `Replication` to avoid that race condition, I noticed that for whatever reason the third `Replication` never got to [this line](https://github.com/couchbase/couchbase-lite-java-core/blob/master/src/main/java/com/couchbase/lite/Database.java#L1871), which means [this line](https://github.com/couchbase/couchbase-lite-java-core/blob/master/src/main/java/com/couchbase/lite/Database.java#L1289) would cause the surrounding while loop to keep going for 60 seconds.
* In general as a naive user I wouldn't expect `Database.close()` to even have the potential to block the thread. In other words I would suggest that potential should either be removed, or at least put as an API doc comment on the method.
* [Database.allReplicators](https://github.com/couchbase/couchbase-lite-java-core/blob/master/src/main/java/com/couchbase/lite/Database.java#L102) is essentially grow-only. You could argue that this Set becoming big enough to cause problems is maybe a misuse of the library, but I think "garbage collecting" it somehow is warranted. Or maybe just getting rid of it completely since at a shallow glance it doesn't seem to do much that is important.
* Again as a user in general I would expect callbacks to `Replication.ChangeListener` to happen on the same thread I kicked things off from, or at least the main thread. It didn't trip me up specifically because I'm always on the lookout for these kinds of things, but I mention it because it's the kind of thing that can easily trip up junior devs (or tired senior devs) and cause undesirable race conditions. I realize there's a performance aspect to this, the extra delay of passing something to the main thread, so maybe that factors in. Or maybe you could make it an option in `ManagerOptions`.
* If you explicitly call `Replication.stop()` inside a `Replication.ChangeListener` callback it can interfere with subsequent listeners. If I remember correctly subsequent listeners just weren't called. There are various ways to approach this recursive event dispatching problem, such as cloning the list of listeners and iterating over that list when dispatching instead of the persistent list, or posting the dispatches onto the thread queue. I haven't looked deeply enough into it to suggest a great approach.
* The type of shared-state, `synchronized`-gated multithreading used to manage the `Set`s of `Replication` instances in `Database` worries me a little. Not only because it's partially, sorta to blame for some of the issues I related above, but also because I've been burned by it time and again myself and finally realized it's probably one of those things like memory management in C that mere mortals just suck at once things get too complex. My only practical suggestion (assuming you do this type of multithreading elsewhere) is to slowly move to a pure message-passing-type of approach wherever possible throughout the codebase. I employed the same strategy when developing [SweetBlue](https://github.com/iDevicesInc/SweetBlue) when I ran into a similar complexity wall trying to make the API thread-safe and it worked out very well. Here's a [good post](http://bholley.net/blog/2015/must-be-this-tall-to-write-multi-threaded-code.html) on the subject, and some [good discussion](http://bholley.net/blog/2015/must-be-this-tall-to-write-multi-threaded-code.html).

So I hope this doesn't sound too critical or know-it-all. For the most part Couchbase Lite has been magic pixie dust that just works how you want. Considering my company's app is now heavily dependent on Couchbase though, I wanted to offer whatever meager feedback I could and hope that it's helpful in the long term.

I've worked around any issues posed by the points above, so no immediate fixes are needed for me. Glad to discuss anything further though!

**Comment by hideki** [comment]
Hi @dougkoellmer,

Thank you very much for thoughtful feedback. We will address items you reported step by step.
- `Database.close()`: Blocking UI thread for 60 sec is not ideal behavior. I consider the logic of stopping replicator has an issue. By fixing it, `close()` will not block 60 sec. It should finish in less than 1 sec. I think [notifyAll()](https://github.com/couchbase/couchbase-lite-java-core/blob/master/src/main/java/com/couchbase/lite/Database.java#L1871) is never called because the replicator is not entered `STOPPED` state yet. If you hit this issue again, can you capture thread-dump from Android Studio or Android Monitor? We could figure out where the thread hangs.
- `Database.close()`: We also consider asynchronous version of close(). This might take time. We will discuss this internally.
- `Database.allReplicators`: Sorry for we did not pay attention this for long time. [Another user also reported issue about this](https://github.com/couchbase/couchbase-lite-java-core/issues/290). If possible, we will eliminate the `allReplicators` variable from database.
- `Replication.ChangeListener`: Callback from which thread is discussion item. Same thing should be applicable to `Database.ChangeListener`. As you suggested, making it an option could be solution.
- `Replication.stop()` inside a `Replication.ChangeListener()`: [Master branch](https://github.com/couchbase/couchbase-lite-java-core/blob/master/src/main/java/com/couchbase/lite/replicator/Replication.java#L79) uses `CopyOnWriteArrayList` for `changeListeners`variable. It makes copy of list for iteration. This could solve your issue.
- Multi-threading is one of big challenges for CBL Android/Java. We will consider the different approach too.

Thank you again for your helpful inputs!
Hideki

**Comment by dougkoellmer** [comment]
Great! Again my company relies on Couchbase very heavily so if you want another ear for the longer-term multi-threading challenges you're facing please don't hesitate to contact me. I went through many of the same challenges developing SweetBlue and can share what went wrong and what went right.

**Comment by hideki** [comment]
ToDo myself:
- Make ticket for individual items

**Comment by hideki** [comment]
Filed into individual tickets
- `Database.close()` #1175 
- `Database.allReplicators` #290 - existing ticket.
- `Replication.ChangeListener` callback thread #1476
- `Replication.stop()` inside a `Replication.ChangeListener()` #1477
-  Appropriate way to manage replication instances in Database. #1478

**Comment by hideki** [comment]
Individual items tracked by each ticket. I will close this ticket.
