### ISSUE TITLE
Test the library with Java 1.7 and Android Studio 2.1

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-java-core#1380]
From a [forum post](https://forums.couchbase.com/t/deployment-problem-with-new-1-3-0/9377/9), there seems to be an issue when using couchbase-lite-android with Java 1.7 (and probably Android Studio 2.x). We need to verify this.

**Comment by natgross** [comment]
In my case ForestDB was the specific problem.

**Comment by hideki** [comment]
Note:
Android Studio requires JDK 1.8
https://developer.android.com/studio/install.html

**Comment by natgross** [comment]
Android Studio might require jdk8 to run for itself, but every project can be configured to compile with 7 or 6 for distribution. If your library is compiled with jdk8, you are forcing developers to target jdk8 for their apk's, which might be impossible in many cases, due to other libraries included in the build.

**Comment by hideki** [comment]
Hi @natgross,

I have tried to reproduce this issue, but so far I could not reproduce this issue.
My test env:
- JDK 1.7 (javac 1.7.0_79)
- Android Studio 2.1.3

**Comment by hideki** [comment]
Notes:

Our libraries for Android are specified source and target compatibility to 1.6. I believe this issue should be occurred.
```
sourceCompatibility = JavaVersion.VERSION_1_6
targetCompatibility = JavaVersion.VERSION_1_6
```

https://github.com/couchbaselabs/couchbase-lite-java-forestdb/blob/master/build-android.gradle#L8-L9
https://github.com/couchbase/couchbase-lite-java-native/blob/master/sqlite-custom/build-android.gradle#L8-L9
https://github.com/couchbase/couchbase-lite-java-native/blob/master/sqlcipher/build-android.gradle#L8-L9
https://github.com/couchbase/couchbase-lite-java-core/blob/master/build.gradle#L6

However
couchbase-lite-android Module is not specified compatibility
https://github.com/couchbase/couchbase-lite-android/blob/master/build.gradle

**Comment by hideki** [comment]
Hi @natgross,

I am using customized version of GrocerySync-Android (https://github.com/couchbaselabs/GrocerySync-Android/blob/master/GrocerySync-Android/build.gradle). I tried both SDK 22 and 23. However, I could not reproduce the problem.

I need your additional input to reproduce the problem.

Thanks!
Hideki

**Comment by natgross** [comment]
@hideki Ok. Will try to pinpoint it again. But just to make sure,
1. The jdk7 is 64 bit (in my case on Windows 10).
2. You actually deploy the apk to a device. This, because oddly enough the build passes with no errors. The error comes up when deploying the apk (in my case via usb adb) to a device. Deployment fails.
Thanks

**Comment by hideki** [comment]
HI @natgross,
Thank you for your inputs.
1. -> I am using OSX 64bit. So JDK7 is 64bit.
2. -> I deploy from Android Studio. Should I deploy *APK* using *adb* to the *real device*?

**Comment by natgross** [comment]
@hideki 
I also deployed from Android Studio. The point I was making was, that not to a virtual device, but to a real hardware device via usb (AS uses adb to do that anyhow), which deploys the debug version of the apk. (as opposed to an apk to be distributed in the play store.)
nat
ps. I tried real hardware devices, on Android 4.2, Android 5.1, Android 6.0.

**Comment by hideki** [comment]
Hi @natgross 

I tried to install apk with adb command. But I still can not reproduce it.

Don't you mind to create super simple Android project to reproduce this?

**Comment by natgross** [comment]
I have upgraded to the latest jdk7 and simplified the project a little, and tweaked parameters, but upon deployment to Android 6 hardware, I get the following err. (Only if forestdb is also included.)
Note that the main error is that a dependency is compiled with Java 8.
(Also please see my next comment on this issue.)
`Error:Error converting bytecode to dex:
Cause: Dex cannot parse version 52 byte code.
**This is caused by library dependencies that have been compiled using Java 8 or above.**
If you are using the 'java' gradle plugin in a library submodule add 
targetCompatibility = '1.7'
sourceCompatibility = '1.7'
to that submodule's build.gradle file.
Error:1 error; aborting
:app:transformClassesWithDexForDebug FAILED
Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\opt\jdk7u79_64\bin\java.exe'' finished with non-zero exit value 1
Information:BUILD FAILED
Information:3 errors `

**Comment by hideki** [comment]
http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Setting-language-level
```
android {
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_6
        targetCompatibility JavaVersion.VERSION_1_6
    }
}
```
We might need to specify compatibility options in `android/compileOptions`.

**Comment by natgross** [comment]
@hideki Yes, I can try to really simplify project. That would be great for pinpointing the problem, but what would it help in real life? You can't demand developers to change their app library structure, in order to deploy CBL 1.3.x forestdb. Please be aware that these apps (yes I have a few with cbl) did NOT have this problem with cbl version 1.2.x. The ONLY thing changed was upgrading to CBL 1.3.x

**Comment by natgross** [comment]
I will try with "sourceCompatibility JavaVersion.VERSION_1_6" but it might cause problems with other of my modules that need 1.7 (I think, not sure, Android 6x, Marshmallow.)

**Comment by natgross** [comment]
How about this, for testing, please compile 1.3x with jdk7 and I'll give it a spin. Leaving everything else the same.
Thanks,
nat

**Comment by hideki** [comment]
@natgross, 
We are building release version on our build server that JDK 1.8 is installed and is used. And we needed to move to 1.8 from 1.7 to support Android N. We don't have choice to use JDK 1.7 for v1.3.x or higher.
Thanks,
Hideki

**Comment by natgross** [comment]
@hideki (Good Morning)
Following did NOT solve the problem. (But am trying other things. I'll keep you posted.)
android {
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_6
        targetCompatibility JavaVersion.VERSION_1_6
    }
}

**Comment by natgross** [comment]
@hideki I have tried tons of possibilities. You name it - I tried it. Including Android Studio 2.2 beta.
On a SIMPLE project.
Including targeting and/or compiling Android 24/23/22.
Including With/Without source-Target compat options. Version_1_6 and Version_1_7.
Including the latest java jdk's 8 and 7.
Including giving 5 gig ram heap space for javac &Gradle.
Also turned off Studio's Instant Run feature.
Result:
FAIL FAIL FAIL. It doesn't like the ForestDB Constants.class. (But I suspect that its a false message.)
The following facts remain:
1. With CBL 1.3.0 - without forestdb, it works just fine.
2. With CBL 1.3.0 - and with forestdb it fails with the SAME message (posted above) in ALL of the environment-combinations mentioned in this comment.
3. With CBL 1.2.1 and with forestdb it works just fine.
-------------------------------
Maybe someone in your org can test on a Windows 10 machine.

**Comment by hideki** [comment]
We build CBL Android with `sourceCompatibility JavaVersion.VERSION_1_6` including ForestDB.

Could you please try version `1.3.1-21`

http://files.couchbase.com/maven2/com/couchbase/lite/couchbase-lite-android/1.3.1-21/

you need to specify custom maven repo to use this.

see https://github.com/couchbase/couchbase-lite-android#using-latest-official-release

**Comment by hideki** [comment]
I also recommend to delete gradle cache (`~/.gradle/caches`)

**Comment by natgross** [comment]
1. I shall try 1.3.1-21
2. I don't understand the relevance in that you build with `sourceCompatibility JavaVersion.VERSION_1_6` since the source code itself uses Java 8 specific features. Anyhow, I did follow your recommendation on that.
3. re: gradle cache. I regularly do File-->Invalidate caches between significant test changes. (Boy does that take time to index afterwards.) I assume it also wipes the Gradle cache.
nat

**Comment by hideki** [comment]
Hi @natgross,

From your error message, the problem could be that couchbase-lite-android-forestdb.jar was compiled by JDK 1.8, but it does not work with JRE 1.7. As couchbase-lite-android-forestdb's build file is not correctly specified targetCompativility, the jar file could be 1.8 compatible binary files. It could cause the problem.

As we need to support old Android APIs, so target should be 1.6. And also our source codes don't use 1.7 or 1.8 features. This is reason we specify 1.6.

If your issue is what I expect, 1.3.1-21 could fix your issue.

Thanks!

**Comment by natgross** [comment]
> From your error message, the problem could be that couchbase-lite-android-forestdb.jar was compiled by JDK 1.8, but it does not work with JRE 1.7.
Although my original post did use jdk/jre7, my latest testing from today (as I mentioned in my earlier post from today) was also on pure jdk/jre 8, Using jdk8u101.

**Comment by hideki** [comment]
I tried to say jar files which are provided by Couchbase are compiled by JDK 1.8 since v1.3.0.

**Comment by natgross** [comment]
@hideki About the url http://files.couchbase.com/maven2/com/couchbase/lite/couchbase-lite-android/1.3.1-21/,
What about the forestdb jar?

**Comment by hideki** [comment]
http://files.couchbase.com/maven2/com/couchbase/lite/couchbase-lite-android-forestdb/1.3.1-21/

**Comment by natgross** [comment]
The news is... GOOD!! @hideki 
**ALL TESTS PASS.**
"ALL TESTS" = 
[all tests using jdk8u101, 1.3.1-21]
1. android compile **sdk 24**.
2. android compile **sdk 23**
3. targetSdkVersion 24 / 23 / 22 . Note. For both sdk 24, and sdk 23.
4. compileOptions-block setting 1_6. Pass for all of the above.
5. compileOptions-block setting 1_7. Pass for all of the above.
6. compileOptions-block NONE. No special compile options; _and still PASS_. For all of the above combinations!
Whew!
nat

**Comment by hideki** [comment]
@natgross 
Thank you very much for testing all combination and all your helps!
