### ISSUE TITLE
v1.3.1's replication speed is slower than 1.3.0.

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-java-core#1416]
https://github.com/couchbase/couchbase-lite-java-core/wiki/Performance-Test-Result

**Comment by pasin** [comment]
ATT: @sethrosetter

**Comment by pasin** [comment]
1. The tests for pull replication (Test07_PullReplication) in 1.3.0 were invalid because in 1.3.0 the single shot pull replicator can pull up to only 50 docs (See https://github.com/couchbase/couchbase-lite-android/issues/955).

2. I have run the Test06_PushReplication on both 1.3.0 and 1.3.1 and the results are pretty consistent. With 1000 docs and 1K each, 1.3.0 is 2217 ms and 1.3.1 is 2165 ms. The tests are run on my home WiFi with Nexus 5X / Android 6.0.1.

**Comment by hideki** [comment]
@pasin thank you

**Comment by hideki** [comment]
Note:

### Push: 
- As @pasin wrote in previous message, push repl performances are almost same between 1.3.0 and 1.3.1.

### Pull:
- In addition to [Android issue 995](https://github.com/couchbase/couchbase-lite-android/issues/955), we fixed https://github.com/couchbase/couchbase-lite-android/commit/c690c74581a5d79d32678b3582ecec5d51283def#diff-a9223f5ecf4d862de16f6f0cb3b74644. Any test results of pull replication which were measured before 1.3.0 are invalid because of test is not correctly implemented.

**Comment by hideki** [comment]
Updated result: https://github.com/couchbase/couchbase-lite-java-core/wiki/Performance-Test-Result
