### ISSUE TITLE
Android app freezes; 3 ANR traces provided; issues since CBL 1.3.0

### ISSUE THREAD

**Issue by benjaminglatzeder** [couchbase/couchbase-lite-java-core#1449]
Setup:
Android app
CBL 1.3.0
SQLite storage (not forestDb)
Android OS: 4.4, 5.1, 6.0
Sources of ANR traces and additional info is from Google Play Dev Console
Both replications set to continuous

User presses a button in app, app writes to storage. The updateDocument method is run on the UI-thread. The experience is often slow and sometimes shows an ANR dialog. The issues seem to appear since the last app update with CBL 1.3.0. Before that the updateDocument method took less than 30ms on average. 

Reproducibility: Difficult to reproduce. To me it looks like that there is a deadlock in CBL/SQLite code

[Traces](https://gist.github.com/benjaminglatzeder/51583115746a0d26032b3f6d1a0fafc8)

Similar issues posted on https://forums.couchbase.com
https://forums.couchbase.com/t/cbl-freezes-app-full-anr-trace-provided/10048/1
https://forums.couchbase.com/t/updating-a-document-takes-375x-longer-after-a-few-updates-app-freezes/9974
https://forums.couchbase.com/t/android-app-freezes-because-of-cbl-because-of-sg-cb-server/9997

**Comment by hideki** [comment]
@benjaminglatzeder,

CBL Android enables multi SQLite connections, maximum is 4. However write connection is 1. From stack trace, pull replications are middle of deleting or inserting record while main thread is waiting for connection. I recommend to use [Database.runAsync()](http://developer.couchbase.com/documentation/mobile/1.3/develop/references/couchbase-lite/couchbase-lite/database/database/index.html#void-runasyncrunasyncdelegate-delegate) or android's AsyncTask to insert document instead of inserting document from main thread.

- Main thread to wait: https://gist.github.com/benjaminglatzeder/51583115746a0d26032b3f6d1a0fafc8#file-gistfile2-txt-L175-L217
- Pull replication to delete record in SQLite: https://gist.github.com/benjaminglatzeder/51583115746a0d26032b3f6d1a0fafc8#file-gistfile2-txt-L1037-L1072
- Pull replication to insert record in SQLite: 
https://gist.github.com/benjaminglatzeder/51583115746a0d26032b3f6d1a0fafc8#file-gistfile3-txt-L1418-L1445

**Comment by benjaminglatzeder** [comment]
Before I read your comment I build a sample Android app with CBL 1.3.1 and data is only saved locally.

The data modell in the project is PersonPOJO. Persons are stored in a single document. I know that this is bad practice but I'd like to mimic the data modell in my production app. The JSON looks like this after 2 persons were added:

**Comment by hideki** [comment]
Todo: Test sample app

**Comment by benjaminglatzeder** [comment]
Update:

@hideki I very much value your time and there is a good chance that you do not have to invest anymore time on this issue. I'm in contact with enterprise support and the problem might be that revisions are never pruned when a document has conflicts. The reason is that I never solve conflicts on the client-side. I will update this thread if implementing conflict solving will have fixed the issue

**Comment by hideki** [comment]
@benjaminglatzeder,
Thank you for your update. Please keep posting status. Thank you!

**Comment by benjaminglatzeder** [comment]
There were no issues in the last days. Implementing conflict resolution on the client side fixed the issue. [Here](https://forums.couchbase.com/t/solve-conflicts-on-client-side-android/10424) is how I implemented it for **my use case**. Closing this issue.
