### ISSUE TITLE
Image attachment not sync'ing from .NET to Android

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/couchbase-lite-java-core#1578]
Using Android 1.4-30

- Create list on .NET (1.4-31) -> Share with iOS and Android (SQLite / ForestDB)
- Create a task (.NET)
- Update w/ image (.NET)
- Everyone sees the image except for android.

**Comment by hideki** [comment]
Note to Self:

This issue is reproducible with Android to Android.
It seems any document updates are not reflected.

Reproduce Conditions:
- Device A: Nexus 6 - Android 6.0.1, Device B: Genymotion - Android 4.4.4
- Both uses ForestDB with Encryption
- Both task check and task image are not reflected.

ToDos:
- Test with SQLite
- To isolate issue is in push, pull,livequery, or application UI

**Comment by hideki** [comment]
Note to self
- SQLite to SQLite => this is not reproducible

**Comment by hideki** [comment]
Note to Self:
- Push replication from Device A is fine.
- Pull replication to Device B which uses ForestDB is also fine.

**Comment by hideki** [comment]
TasksFragment.java of ToDo Android

```java
    private void setupViewAndQuery() {
        com.couchbase.lite.View view = mDatabase.getView("task/tasksByCreatedAt");
        if (view.getMap() == null) {
            view.setMap(new Mapper() {
                @Override
                public void map(Map<String, Object> document, Emitter emitter) {
                    String type = (String) document.get("type");
                    if ("task".equals(type)) {
                        Map<String, Object> taskList = (Map<String, Object>) document.get("taskList");
                        String listId = (String) taskList.get("id");
                        String task = (String) document.get("task");
                        ArrayList<String> key = new ArrayList<String>();
                        key.add(listId);
                        key.add(task);
                        emitter.emit(key, null);
                    }
                }
            }, "5.0");
        }
```

map/reduce function emits `key` and `null`. `key` value is composed of `listId` and `task` value. In case of updating Photo or CheckBox, `key` value will not be changed, also `value` is kept `null`. In this case, ForesDB does not fire the notification, because indexed value is not changed. However, SQLite fires even index value is not changed. This is known implementation difference. Need to be handled by Application.

**Comment by hideki** [comment]
Ref: https://github.com/couchbaselabs/mobile-training-todo/issues/108
