### ISSUE TITLE
Replication support for SNI (Server Name Indication) with https

### ISSUE THREAD

**Issue by fede87** [couchbase/couchbase-lite-java-core#330]
I have this exception:

E/RemoteRequest(5430): javax.net.ssl.SSLException: hostname in certificate didn't match: < couchdbhost.domain.com > != < domain.com > OR < domain.com > OR < www.domain.com >

while creating pull replication from database with haproxy configuration and SNI for SSL certificates.

Is it possible to add SNI support ?

I've found here some workarounds using HttpsURLConnection and customizing HttpClient:

http://blog.dev001.net/post/67082904181/android-using-sni-and-tlsv1-2-with-apache-httpclient
https://github.com/Crazyphil/acra/commit/9a28add2971b4e6469b267c367ec5c00022b7715

**Comment by hideki** [comment]
Hello @fede87 

I wrote the sample code that describes how to set custom SSLSocketFactory to CBL Android/Java. Sample's custom SSLSocketFacgtory is based on TlsSniSocketFactory (https://github.com/Crazyphil/acra/commit/9a28add2971b4e6469b267c367ec5c00022b7715) that you mentioned in previous your comment.

Sample code:
https://gist.github.com/hideki/fa362a590e4b96800762#file-issue330test

We don't have the test environment for this issue. Could you please verify if this solution works with your environment? Please let us know if it works for you.

Thanks,
Hideki

**Comment by fede87** [comment]
Thank you @hideki  for your help. 

I'll let you know in the next few days if your solution works in my environment.

Thanks,

Fede

**Comment by lassebn** [comment]
Over a year later, and the sample code that @hideki provided could help me - great! :)

However, I have some questions for clarification:

- This update to our code is not needed on devices running Android 6, API v. 23. I'm guessing that this is because [Android is moving from OpenSSL to BoringSSL](http://developer.android.com/about/versions/marshmallow/android-6.0-changes.html#boringSSL), but do you know?
- [The Apache HTTP Client is removed](http://developer.android.com/about/versions/marshmallow/android-6.0-changes.html#behavior-apache-http-client). Do you have plans to move away from the Apache HTTP Client?

Thank you for your sample code and time!

**Comment by hideki** [comment]
@lassebn 

> This update to our code is not needed on devices running Android 6, API v. 23. I'm guessing that this is because Android is moving from OpenSSL to BoringSSL, but do you know?

This is good news. Thank you for sharing.

> The Apache HTTP Client is removed. Do you have plans to move away from the Apache HTTP Client?

We knew it, but we did not start to work for it.  https://github.com/couchbase/couchbase-lite-java-core/issues/708

Cheers!
