### ISSUE TITLE
Don't persist cookie without max-age or expires property

### ISSUE THREAD

**Issue by tleyden** [couchbase/couchbase-lite-java-core#353]
From https://github.com/couchbase/couchbase-lite-ios/issues/552#issuecomment-66956869:

> That sounds like an Android bug, actually. If the cookie doesn't have a max-age or expires property then it is not persistent, and the client should not save it across app launches.

**Comment by hideki** [comment]
@tleyden, please let me help to understand this ticket.

In case of setting a cookie explicitly to replicator from PhoneGap app, a cookie is not persisted with using PersistentCookieStore class. I confirmed it by adding additional logging message into the class. Also currently PhoneGap app on Android does not support to set cookie implicitly.

If I understand our code correctly, the cookie is persisted through PersistentCookieStore only by calling setCookie() java method from android/java app which uses CBL (PhoneGap app can not call this method.). Methods of CBL java core do not call setCookie() method internally. In addition, PersistentCookieStore includes logic to clean expired cookie and to ignore expired cookie. So it does not allow to persist an expired cookie.

Because of above observations, I infer that customer was discussing about cookie store of Android WebView that is used by PhoneGap app. In this case, it is out of our control because WebView is part of Android platform.  Original ticket: https://github.com/couchbase/couchbase-lite-ios/issues/552

What do you think?

**Comment by tleyden** [comment]
Ok, it sounds like we can close this bug then.
