### ISSUE TITLE
RemoteRequestCompletionBlock java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by tleyden** [couchbase/couchbase-lite-java-core#361]
From a [google group](java.util.ConcurrentModificationException) post:

https://groups.google.com/forum/#!searchin/mobile-couchbase/java.util.ConcurrentModificationException/mobile-couchbase/TIfxH5SpkBE/Oidym_uLfSYJ

Hi, i encountered crashed using cblite 1.0.3.

```
12-17 04:50:59.732: E/RemoteRequest(16702): RemoteRequestCompletionBlock throw Exception
12-17 04:50:59.732: E/RemoteRequest(16702): java.util.ConcurrentModificationException
12-17 04:50:59.732: E/RemoteRequest(16702):     at java.util.AbstractList$SimpleListIterator.next(AbstractList.java:62)
12-17 04:50:59.732: E/RemoteRequest(16702):     at java.util.AbstractList$SubAbstractList$SubAbstractListIterator.next(AbstractList.java:201)
12-17 04:50:59.732: E/RemoteRequest(16702):     at java.util.AbstractCollection.toArrayList(AbstractCollection.java:349)
12-17 04:50:59.732: E/RemoteRequest(16702):     at java.util.AbstractCollection.toArray(AbstractCollection.java:339)
12-17 04:50:59.732: E/RemoteRequest(16702):     at java.util.ArrayList.addAll(ArrayList.java:184)
12-17 04:50:59.732: E/RemoteRequest(16702):     at com.couchbase.lite.replicator.PullerInternal.pullRemoteRevisions(PullerInternal.java:239)
12-17 04:50:59.732: E/RemoteRequest(16702):     at com.couchbase.lite.replicator.PullerInternal$7.onCompletion(PullerInternal.java:624)
12-17 04:50:59.732: E/RemoteRequest(16702):     at com.couchbase.lite.support.RemoteRequest.respondWithResult(RemoteRequest.java:305)
12-17 04:50:59.732: E/RemoteRequest(16702):     at com.couchbase.lite.support.RemoteMultipartDownloaderRequest.executeRequest(RemoteMultipartDownloaderRequest.java:127)
12-17 04:50:59.732: E/RemoteRequest(16702):     at com.couchbase.lite.support.RemoteMultipartDownloaderRequest.run(RemoteMultipartDownloaderRequest.java:46)
12-17 04:50:59.732: E/RemoteRequest(16702):     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
12-17 04:50:59.732: E/RemoteRequest(16702):     at java.util.concurrent.FutureTask.run(FutureTask.java:234)
12-17 04:50:59.732: E/RemoteRequest(16702):     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
12-17 04:50:59.732: E/RemoteRequest(16702):     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
12-17 04:50:59.732: E/RemoteRequest(16702):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
12-17 04:50:59.732: E/RemoteRequest(16702):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
12-17 04:50:59.732: E/RemoteRequest(16702):     at java.lang.Thread.run(Thread.java:838)
```

Any idea why it happened?
I revert back to 1.0.2 and works just fine.

**Comment by tleyden** [comment]
Try to flesh with a unit test:

* Start pusher and puller
* Look for these exceptions

If not, can be fixed by inspecting code + stack trace

**Comment by hideki** [comment]
Hi @sleith,

Could you please provide more detailed information to understand this issue?

- Is this issue could be reproducible with simple pull replication with simple document?
- Is this still reproducible with 1.0.4? or master branch?

Any additional information are appreciated.

Thanks,
Hideki

**Comment by hideki** [comment]
Note to self:

https://github.com/couchbase/couchbase-lite-java-core/blob/release/1.0.3.1/src/main/java/com/couchbase/lite/replicator/PullerInternal.java#L239
```
bulkWorkToStartNow.addAll(bulkRevsToPull.subList(0, nBulk));
```

Notes:
- `bulkWorkToStartNow` is ArrayList which is not thread safe. But it is declared in the same method. This should not be issue. 
- bulkRevsToPull is also ArrayList. And it is instance variable of `PullerInternal` class. This could accessed from multiple threads.
- http://docs.oracle.com/javase/7/docs/api/java/util/ConcurrentModificationException.html
- http://docs.oracle.com/javase/7/docs/api/java/util/ArrayList.html
- https://commons.apache.org/proper/commons-collections/javadocs/api-3.2.1/org/apache/commons/collections/collection/SynchronizedCollection.html

Solution:
- Change `bulkRevsToPull` to synchronized List.
- bulkWorkToStartNow.addAll() should by synchronized by `synchronized(bulkRevsToPull)` because addAll(List) iterates parameter list.
