### ISSUE TITLE
LiveQuery not getting called for non current revisions

### ISSUE THREAD

**Issue by jamiltz** [couchbase/couchbase-lite-java-core#463]
While working on conflict resolution for todo lite android, I noticed that the live query change listener doesn't get called when new non-current revisions are inserted.

See video http://cl.ly/ZwEe, couchbase lite picks "update 2" as the current revision. Emulator on the right only shows the conflict icon when reloading the list view, the live query doesn’t fire when the "update 1" revision is pulled from sync gateway.

A workaround is to register for database change events and call the query's getRows() method to reload the query.

I will test on iOS to see if it's the same behaviour.

**Comment by tleyden** [comment]
> I will test on iOS to see if it's the same behaviour.

@Jamiltz what did you find?

**Comment by Takhion** [comment]
Related to #405?

**Comment by jamiltz** [comment]
@tleyden Tested on iOS and it's the same behaviour as on Android. Live Query doesn't trigger when conflicting revisions are saved. The database change event however does trigger.

@Takhion Yes, it seems to be related to that.

But I think the use case is different. Here we would actually need the view to index all revisions (even the conflicting ones) so that the live query triggers for any change on any conflicting revision.

**Comment by zgramana** [comment]
We'll need to discuss this one as a team.

**Comment by hideki** [comment]
TODO: setup team meeting for discuss this ticket including @Jamiltz

**Comment by snej** [comment]
So, this is working correctly. LiveQuery triggers a notification when the _query results_ change, not when the underlying _documents_ change. In particular, the query results aren't affected by non-current revisions, since only the current/winning revision gets indexed.

This kind of issue comes up frequently, where someones uses a LiveQuery to run a GUI that displays attributes of the document that aren't part of the query results. (Maybe we shouldn't have made it so easy to go from the QueryRow to the source Document...) The general answer is "if you want to display property X, you need to emit it". However, in this case that doesn't apply because you want to display the document's conflict state and the map function can't see that.

In the long run we can add a document metadata property accessible from the map function that indicates that the doc is in conflict. (We just have to design this carefully to avoid hurting indexing performance.) In the short term, you can watch database-change notifications to detect when documents in your GUI become conflicted.

**Comment by jamiltz** [comment]
:+1:
