### ISSUE TITLE
Using PipedInputStream and PipedOutputStream in URLConnection can cause deadlock (see issue 57 in couchbase-lite-java-listener)

### ISSUE THREAD

**Issue by fpum** [couchbase/couchbase-lite-java-core#667]
The URLConnection class uses PipedInputStream and PipedOutputStream. This can cause a deadlock when writing and reading on the same thread (see issue 57 in couchbase-lite-java-listener).

**Comment by hideki** [comment]
Original bug report: couchbase/couchbase-lite-java-listener/issues/57

**Comment by jamiltz** [comment]
Note: I've taken @fpum's demo to reproduce the issue and tested with 1.1.0-532 and 1.2. They can be found below. It uses feed=continuous. I haven't tested with feed=longpoll or feed=normal.

With 1.1.0-532: http://cl.ly/3W311m2b3V2n
With 1.2: http://cl.ly/3e353V2r1h0W

The listener hangs on the 1st change with 1.2 and hangs on the 5th change event with 1.1.0-532

![comparison](https://cloud.githubusercontent.com/assets/2589337/12867853/5639d66e-cd12-11e5-849c-be0b16082565.png)

**Comment by jamiltz** [comment]
Notes: I forgot to add the network permissions in the demo app. It's required otherwise the demo app may error out.

```
<uses-permission android:name="android.permission.INTERNET"/>
```

Demo working (http://cl.ly/2v47030e3m3o) with the master branch from @fpum's fork and changes are continuously displayed:

![fix](https://cloud.githubusercontent.com/assets/2589337/12868253/15da1624-cd1c-11e5-879e-f4c1b1fc628b.png)
