### ISSUE TITLE
Implement ForestDB Storage Engine

### ISSUE THREAD

**Issue by zgramana** [couchbase/couchbase-lite-java-core#703]
Classes to be implemented:
- ForesetDBStore.java  - 32 public methods to be implemented with supporting protected/private methods
- ForestDBViewStore.java - 17 public methods to be implemented with supporting protected/private methods

**Comment by hideki** [comment]
Aug 21st, 2015 Status
- ForestDBStore: 3 unimplemented methods remains
- ForestDBViewStore: 7 unimplemented methods remains

**Comment by hideki** [comment]
Aug 26th, 2015 Status
Followings are remaining.
- Most Unit Tests pass except ReplicatorTest.testAllLeafRevisionsArePushed() which is common issue with iOS.
- Need to work for Manager.replaceDatabase() method that only allows SQLite -> SQLite and ForestDB -> ForestDB. No SQLite->ForestDB and ForestDB -> SQLite
- Way to switch SQLite and ForestDB.
- Some ForestDBStorage class's methods are not implemented because they are not used from Unit Test. If necessary, need to implement them.
- ForestDB module packaing
