### ISSUE TITLE
Need to investigate the slowness of testSymmetricKey & testCompactEncryptedDB tests on Android 4.x devices

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-java-core#754]
Samsung S3 Android 4.1.2
- testCompactEncryptedDB: 4sec
- testCompactEncryptedDB: 3sec
- testSymmetricKey: 4sec
- testSymmetricKey: 4sec

Above test cases don't contains wait/sleep codes in the test. It could be faster.

**Comment by pasin** [comment]
Fixed by f50f9a6d00cd3c0e95d7ac7585fe16b2bc5d13ae, e925ee4d8023f5f5695202b8cad0afa40ac11860, https://github.com/couchbase/couchbase-lite-android/commit/743027e40b61059db0c49f991e9803d1aa671460

Running on Nexus 4 Emulator with API 19.
DURATION: testCompactEncryptedDB: 1sec
DURATION: testSymmetricKey: 0sec
