### ISSUE TITLE
Simple benchmarks of SQLCipher performance

### ISSUE THREAD

**Issue by zgramana** [couchbase/couchbase-lite-java-core#777]

**Comment by pasin** [comment]
##Nexus 4
#### Test1_CreateDocs

| num docs | doc size | SQLite (ms) | SQLCipher (ms) | SQLCipher-Encrypted (ms) | Android SQLCipher (ms) | Android SQLCipher-Encrypted (ms) |
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |
|100|1K|269|311 (+16%)|427 (+59%)|326 (+21%)|414 (+54%)|
|100|10K|370|455 (+23%)|646 (+75%)|400 (+8%)|556 (+50%)|
|100|100K|1354|1635 (+21%)|2662 (+97%)|1686 (+25%)|2316 (+71%)|

#### Test17_ReadDocs

| num docs | doc size | SQLite (ms) | SQLCipher (ms) | SQLCipher-Encrypted (ms) | Android SQLCipher (ms) | Android SQLCipher-Encrypted (ms) |
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |
|100|1K|153|171 (+12%)|182 (+19%)|172 (+20%)|183 (+20%)|
|100|10K|205|227 (+11%)|306 (+49%)|246 (+20%)|291 (+42%)|
|100|100K|595|628 (+6%)|1399 (+135%)|687 (+15%)|1124 (+89%)|

##Nexus 9
#### Test1_CreateDocs

| num docs | doc size | SQLite (ms) | SQLCipher (ms) | SQLCipher-Encrypted (ms) |
| ------------- | ------------- | ------------- | ------------- | ------------- |
|100|1K|100|116 (+16%)|160 (+60%)|
|100|10K|153|167 (+14%)|235 (+60%)|
|100|100K|494|550 (+11%)|872 (+77%)|

#### Test17_ReadDocs

| num docs | doc size | SQLite (ms) | SQLCipher (ms) | SQLCipher-Encrypted (ms) |
| ------------- | ------------- | ------------- | ------------- | ------------- |
|100|1K|68|71 (+4%)|76 (+12%)|
|100|10K|86|86 (+0%)|115 (+33%)|
|100|100K|197|182 (-8%)|458 (+132%)|

**Comment by hideki** [comment]
@pasin,

- I'd like to know where SQLCipher slowness comes from? Is it because of not using Android SQLDatabase cursor?

- What is difference between SQLCipher-Encrypted  and Android SQLCipher-Encrypted ? I think you tested with Android?

**Comment by pasin** [comment]
> What is difference between SQLCipher-Encrypted and Android SQLCipher-Encrypted ? I think you tested with Android?

The different between SQLCipher and Android SQLCipher is that:
- SQLCipher-Encrypted is our own ported SQLiteDatabase wrapper with SQLCipher + libtomcrypt
- Android SQLCipher is https://github.com/sqlcipher/android-database-sqlcipher library which is SQLCipher + openssl

> I'd like to know where SQLCipher slowness comes from? Is it because of not using Android SQLDatabase cursor?

- Both our own wrapper and the android-database-sqlcipher library have similar overhead even there is no encryption enabled. I guessed the slowness coming from the SQLCipher itself.
- SQLCipher-Encrypted is slower than Android SQLCipher-Encrypted mostly because libtomcrypt is slower than openssl. I did a quick test by swapping the libtomcrypt with openssl and I got pretty much the same performance as the Android SQLCipher-Encrypted. Openssl provides better performance with build and maintenance cost (especially for windows users). We need to evaluate if we want to use openssl.

**Comment by pasin** [comment]
With the new compiling options, we are able to match Android SQLCipher library.

**Comment by pasin** [comment]
Assigned to @zgramana for reviewing.

**Comment by hideki** [comment]
Remaining task could be done with #786
