### ISSUE TITLE
Support encryption in ForestDBStore

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-java-core#827]
At cbforest level, encryption is ready https://github.com/couchbase/couchbase-lite-java-core/issues/811

Needs to implement encryption functionalities into ForestDBStore

This task depends on #804, and others?

**Comment by pasin** [comment]
I have implemented the Java API (except #804). All tests pass except testUnEncryptedDB which ForestDB returns error=-16 (FDB_RESULT_FILE_CORRUPTION) when trying to open an unencrypted database with an encryption key. I understand that we are expecting FDB_RESULT_NO_DB_HEADERS (-38) or FDB_RESULT_CRYPTO_ERROR (-44) based on the iOS implementation.

@snej, what error should the ForestDB return for this case?

**Comment by snej** [comment]
@pasin, Sorry for not replying earlier! If a db file is opened with the wrong encryption key, the data read from it will be random garbage, so the effect is the same as ForestDB opening a garbage file. So far I've found it always fails to find a valid header block in the file and returns `FDB_RESULT_NO_DB_HEADERS `; but looking at the `_filemgr_read_header` function, I think it could think it's found a header if there is a 0xEE byte located on a 4k boundary. In that case it looks like it would return `FDB_RESULT_CHECKSUM_ERROR` because the CRC checksum in the "header" wouldn't match. I'm not sure exactly where `FDB_RESULT_FILE_CORRUPTION` would come from — that's returned from a number of lower-level file I/O calls. Maybe reading the header involves calling one of those functions? I can ask the ForestDB guys.

Anyway, I think we should probably treat `FDB_RESULT_CHECKSUM_ERROR` on open as meaning the encryption key is invalid/missing. I'm a bit unsure about `FDB_RESULT_FILE_CORRUPTION` since that seems it could also be likely to happen with actual corruption in the file...
